const data = [
  { id: 1, name: "Blue Shirt", price: "$200", offprice: "$50", img: "/i1.jpg" },
  {
    id: 2,
    name: "White Shirt",
    price: "$200",
    offprice: "$50",
    img: "/i2.jpg",
  },
  { id: 3, name: "White Gown", price: "$200", offprice: "$50", img: "/i3.jpg" },
  { id: 4, name: "Grey Polo", price: "$200", offprice: "$50", img: "/i4.jpg" },
  { id: 5, name: "Grey Coat", price: "$200", offprice: "$50", img: "/i5.jpg" },
  {
    id: 6,
    name: "Mustard Coat",
    price: "$200",
    offprice: "$50",
    img: "/i6.jpg",
  },
  { id: 7, name: "Pink Suit", price: "$200", offprice: "$50", img: "/i7.jpg" },
  { id: 8, name: "Blue Dress", price: "$200", offprice: "$50", img: "/i8.jpg" },
  { id: 9, name: "Red Set", price: "$200", offprice: "$50", img: "/i9.jpg" },
  {
    id: 10,
    name: "white Dress",
    price: "$200",
    offprice: "$50",
    img: "/i10.jpg",
  },
  {
    id: 11,
    name: "Yellow Set",
    price: "$200",
    offprice: "$50",
    img: "/i11.jpg",
  },
  {
    id: 12,
    name: "Black Hoodie",
    price: "$200",
    offprice: "$50",
    img: "/i12.jpg",
  },
  {
    id: 13,
    name: "Camo Set",
    price: "$200",
    offprice: "$50",
    img: "/i13.jpg",
  },
  {
    id: 14,
    name: "White Set",
    price: "$200",
    offprice: "$50",
    img: "/i14.jpg",
  },
];

export const getPosts = () => data;
