const data = [
  {
    id: 1,
    name: "Blue Shirt",
    color: "aliceblue",

    category: "coat",
    price: "$200",
    offprice: "$50",
    rating: "4.3",
    totalReviews: "241",
    img: "/i1.jpg",
    images: ["/i1.jpg", "/i1.jpg", "/i1.jpg", "/i1.jpg"],
  },
  {
    id: 2,
    name: "White Shirt",
    color: "aliceblue",
    category: "coat",
    price: "$200",
    offprice: "$50",
    rating: "4.3",
    totalReviews: "241",
    img: "/i2.jpg",
    images: ["/i2.jpg", "/i2.jpg", "/i2.jpg", "/i2.jpg"],
  },
  {
    id: 3,
    name: "White Gown",
    color: "alicewhite",
    price: "$200",
    offprice: "$50",
    rating: "4.3",
    totalReviews: "241",
    img: "/i3.jpg",
    images: ["/i3.jpg", "/i3.jpg", "/i3.jpg", "/i3.jpg"],
  },
  {
    id: 4,
    name: "Grey Polo",
    price: "$200",
    offprice: "$50",
    rating: "4.3",
    totalReviews: "241",
    img: "/i4.jpg",
    images: ["/i4.jpg", "/i4.jpg", "/i4.jpg", "/i4.jpg"],
  },
  {
    id: 5,
    name: "Grey Coat",
    price: "$200",
    offprice: "$50",
    rating: "4.3",
    totalReviews: "241",
    img: "/i5.jpg",
    images: ["/i5.jpg", "/i5.jpg", "/i5.jpg", "/i5.jpg"],
  },
  {
    id: 6,
    name: "Mustard Coat",
    price: "$200",
    offprice: "$50",
    rating: "4.3",
    totalReviews: "241",
    img: "/i6.jpg",
    images: ["/i6.jpg", "/i6.jpg", "/i6.jpg", "/i6.jpg"],
  },
  {
    id: 7,
    name: "Pink Suit",
    price: "$200",
    offprice: "$50",
    rating: "4.3",
    totalReviews: "241",
    img: "/i7.jpg",
    images: ["/i7.jpg", "/i7.jpg", "/i7.jpg", "/i7.jpg"],
  },
  {
    id: 8,
    name: "Blue Dress",
    price: "$200",
    offprice: "$50",
    rating: "4.3",
    totalReviews: "241",
    img: "/i8.jpg",
    images: ["/i8.jpg", "/i8.jpg", "/i8.jpg", "/i8.jpg"],
  },
  {
    id: 9,
    name: "Red Set",
    price: "$200",
    offprice: "$50",
    rating: "4.3",
    totalReviews: "241",
    img: "/i9.jpg",
    images: ["/i9.jpg", "/i9.jpg", "/i9.jpg", "/i9.jpg"],
  },
  {
    id: 10,
    name: "white Dress",
    price: "$200",
    offprice: "$50",
    rating: "4.3",
    totalReviews: "241",
    img: "/i10.jpg",
    images: ["/i10.jpg", "/i10.jpg", "/i10.jpg", "/i10.jpg"],
  },
  {
    id: 11,
    name: "Yellow Set",
    price: "$200",
    offprice: "$50",
    rating: "4.3",
    totalReviews: "241",
    img: "/i11.jpg",
  },
  {
    id: 12,
    name: "Black Hoodie",
    price: "$200",
    offprice: "$50",
    rating: "4.3",
    totalReviews: "241",
    img: "/i12.jpg",
  },
  {
    id: 13,
    name: "Camo Set",
    price: "$200",
    offprice: "$50",
    rating: "4.3",
    totalReviews: "241",
    img: "/i13.jpg",
  },
  {
    id: 14,
    name: "White Set",
    price: "$200",
    offprice: "$50",
    rating: "4.3",
    totalReviews: "241",
    img: "/i14.jpg",
  },
];

export const getPosts = () => data;
